################################################################################
## ShamanOps Base Pipeline | Github Actions | Cloud runner #####################
################################################################################
##
image: 
  name: ghcr.io/shamanops/runners-fedora:stable
  pull_policy: always
  entrypoint: [""]
################################################################################
# Stages
stages:
  - requirements
  - build
  - analysis
  - test
  - deploy
 
################################################################################
# Global variables
variables:
  # For CI Platform:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 0
  # Environments: full-with-drp (dev/stg/prod/drp) | full (dev/stg/prod) | mid (stg/prod) | minimal (prod)
  environments: 'full'
  # Global variables
  customerName: $CI_PROJECT_ROOT_NAMESPACE
  # Project
  projectName: 'default'
  appName: $CI_PROJECT_NAME
  repoUrl: $CI_REPOSITORY_URL
  jobUrl: $CI_JOB_URL
  var2: ${CI_REGISTRY_IMAGE%/*}
  # Approvals
  approvals_timeout: '30m'
  shamanopsBusinessApprovers: ''
  shamanopsTechnicalApprovers: ''
  shamanopsApprovalsDev: 'false'
  shamanopsApprovalsStg: 'false'
  shamanopsApprovalsProd: 'true'
  shamanopsBusinessApproversMinimalProd: '0'
  shamanopsTechnicalApproversMinimalProd: '1'
  # Code language Auto-detection
  code_language_detection_enabled: 'true'
  # Dependency and OS security checker
  security_check_enabled: 'true'
  security_check_blocker: 'false'
  # SAST check | Sonarqube
  code_quality_check_enabled: 'true'
  code_quality_check_blocker: 'false'
  code_quality_check_exlusions: 'test/**'
  code_quality_check_test_exlusions: '**/vendor/**' 
  code_quality_check_test_inclusions: '**/*test*'
  # Stress tests | JMeter
  stress_check_enabled: 'false'
  stress_check_blocker: 'false'
  stress_check_error_rate_max: '15'
  stress_check_thread: '19'
  stress_check_upPeriod: '10'
  stress_check_second: '60'
  # Functional tests | Selenium
  functional_test_enabled: 'false'
  functional_test_blocker: 'false'
  # Verbosity level
  log_level: 'normal'
################################################################################
# Stages
# ------------------------------------------------------------------------------
# Stage 1 - Requirements #######################################################
repository-check:
  tags:
    - self-hosted
  stage: requirements
  rules:
    - when: always
  script:
    - shamanops repository-check
# ------------------------------------------------------------------------------
# Stage 2 - Build ##############################################################
image-build-and-push:
  tags:
    - self-hosted
  stage: build
  script:
    - shamanops image-build
  needs: ["repository-check"]
image-check:
  tags:
    - self-hosted
  stage: build
  script:
    - shamanops image-check
  needs: ["repository-check", "image-build-and-push"]
# ------------------------------------------------------------------------------
# Stage 3 - Analysis ###########################################################
security_check:
  tags:
    - self-hosted
  stage: analysis
  rules:
    - if: $security_check_enabled == 'true' && $security_check_blocker == 'true'
      when: on_success
      allow_failure: false
    - if: $security_check_enabled == 'true' && $security_check_blocker != 'true'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops security-check
sast_check:
  tags:
    - self-hosted
  stage: analysis
  rules:
    - if: $code_quality_check_enabled == 'true' && $code_quality_check_blocker == 'true'
      when: on_success
      allow_failure: false
    - if: $code_quality_check_enabled == 'true' && $code_quality_check_blocker != 'true'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops sast-check
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - DEV environment #########################################################
approvals-dev:
  tags:
    - self-hosted
  stage: deploy
  rules:
    - if: $environments != 'minimal' && $environments != 'mid' && $shamanopsApprovalsDev == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - echo "approvals-dev"
app-create-and-deploy-dev:
  tags:
    - self-hosted
  stage: deploy
  rules:
    - if: $environments != 'minimal' && $environments != 'mid'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy dev
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - STG environment #########################################################
approvals-stg:
  tags:
    - self-hosted
  stage: deploy
  rules:
    - if: $environments != 'minimal' && $shamanopsApprovalsStg == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - echo "approvals-stg"
app-create-and-deploy-stg:
  tags:
    - self-hosted
  stage: deploy
  needs: ["app-create-and-deploy-dev"]
  rules:
    - if: $environments != 'minimal'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy stg
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - PROD environment #########################################################
stress_test:
  tags:
    - self-hosted
  stage: deploy
  needs: ["app-create-and-deploy-stg"]
  rules:
    - if: $stress_check_enabled == 'true' && $stress_check_blocker == 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: false
    - if: $stress_check_enabled == 'true' && $stress_check_blocker != 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops stress-check
approvals-prod:
  tags:
    - self-hosted
  stage: deploy
  needs:
    - job: app-create-and-deploy-stg
      optional: false
    - job: stress_test
      optional: true
  rules:
    - if: $shamanopsApprovalsProd == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - echo "approvals-prod"
app-create-and-deploy-prod:
  tags:
    - self-hosted
  stage: deploy
  needs: ["approvals-prod"]
  script:
    - shamanops app-create-and-deploy prod
app-create-and-deploy-drp:
  tags:
    - self-hosted
  stage: deploy
  needs: ["app-create-and-deploy-prod"]
  rules:
    - if: $environments == 'full-with-drp'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy drp
################################################################################
