{
 "title": "Openshift / Golden signals",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SRE - Golden Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "stat",
   "description": "The number of HTTP requests made in the last 1 minute window",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(haproxy_frontend_http_responses_total[1m]))"
    }
   ]
  },
  {
   "title": "Errors per Minute",
   "type": "stat",
   "description": "This is the number of 4xx and 5xx requests in the last minute.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(haproxy_frontend_http_responses_total{code=~\"[4-5].*\"}[1m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (haproxy_frontend_bytes_in_total[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (irate (haproxy_frontend_bytes_out_total[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "stat",
   "description": "Total time for NGINX and upstream servers to process a request and send a response",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg(haproxy_server_http_average_response_latency_milliseconds))",
     "legendFormat": "5th"
    }
   ]
  },
  {
   "title": "Average CPU Usg Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( rate (haproxy_process_cpu_seconds_total[1m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(haproxy_process_virtual_memory_bytes) ",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}