################################################################################
## ShamanOps Base Pipeline | Github Actions | Cloud runner STABLE ##############
################################################################################
##
image: 
  name: registry.shamanops.com/runner/fedora:stable
  pull_policy: always
  entrypoint: [""]
################################################################################
# Stages
stages:
  - requirements
  - build
  - analysis
  - test
  - deploy
 
################################################################################
# Global variables
variables:
  # For CI Platform:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 0
  # Environments: full-with-drp (dev/stg/prod/drp) | full (dev/stg/prod) | mid (stg/prod) | minimal (prod)
  environments: 'full'
  # Global variables
  customerName: $CI_PROJECT_ROOT_NAMESPACE
  # Project
  projectName: 'default'
  appName: $CI_PROJECT_NAME
  appInternalPort: '8080'
  strategyCanaryProd: 'false'
  strategyCanaryStg: 'false'
  strategyCanaryDev: 'false'
  strategyBlueGreenProd: 'false'
  strategyBlueGreenStg: 'false'
  strategyBlueGreenDev: 'false'
  repoUrl: $CI_REPOSITORY_URL
  jobUrl: $CI_JOB_URL
  pipelineId: $CI_PIPELINE_ID
  var2: ${CI_REGISTRY_IMAGE%/*}
  # Approvals
  approvals_timeout: '30'
  shamanopsBusinessApprovers: ''
  shamanopsTechnicalApprovers: ''
  shamanopsApprovalsDev: 'false'
  shamanopsApprovalsStg: 'false'
  shamanopsApprovalsProd: 'true'
  shamanopsBusinessApproversMinimalProd: '0'
  shamanopsTechnicalApproversMinimalProd: '0' 
  # Code language Auto-detection
  code_language_detection_enabled: 'false'
  # Dependency and OS security checker
  security_check_enabled: 'true'
  security_check_blocker: 'false'
  security_check_report_upload: 'false'
  security_check_report_format: 'table'
  # Software Bill of Materials
  sbom_check_enabled: 'false'
  sbom_check_report_upload: 'false'
  sbom_check_report_format: 'table'
  # SAST check
  code_quality_check_enabled: 'false'
  code_quality_check_blocker: 'false'
  code_quality_check_exclusions: 'test/**'
  code_quality_check_test_exclusions: '**/vendor/**' 
  code_quality_check_test_inclusions: '**/*test*'
  code_quality_check_cs_dir: ''
  code_quality_check_cs_nuget_enabled: 'false'
  code_quality_check_cs_nuget_dir: '/nuget'
  code_quality_check_cs_nuget_config: 'NuGet.Config'
  code_quality_check_test_cs_enabled: 'false'
  code_quality_check_test_cs_opencover_reportsPaths: 'tests/**/coverage.opencover.xml'
  # Stress tests
  stress_check_enabled: 'false'
  stress_check_blocker: 'false'
  stress_check_error_rate_max: '15'
  stress_check_thread: '19'
  stress_check_upPeriod: '10'
  stress_check_second: '60'
  # Functional Analysis
  functional_analysis_enabled: 'false'
  functional_analysis_blocker: 'false'
  functional_analysis_test_type: 'playwright'
  functional_analysis_test_storage_enabled: 'false'
  functional_analysis_test_storage_class: 'default'
  functional_analysis_test_path: 'testing'
  functional_analysis_test_timeout: '600'
  # Database Versioning
  db_versioning_enabled: 'false'
  db_versioning_type: 'postgresql'
  db_versioning_changelog_file: 'db.changelog.xml'
  # Verbosity level
  log_level: 'normal'
  # GIT Submodules
  git_submodules_enabled: 'false'
  # Dynamic Envs
  shamanopsDynamicEnvsEnabled: 'false'
  shamanopsDynamicEnvs: 'qa'
  shamanopsTechnicalApproversMinimalDynamicEnvs: '1' 
  shamanopsBusinessApproversMinimalDynamicEnvs: '1' 
  shamanopsApprovalsDynamicEnvs: 'false'
################################################################################
# Stages
# ------------------------------------------------------------------------------
# Stage 1 - Requirements #######################################################
repository-check:
  tags:
    - self-hosted
  stage: requirements
  rules:
    - when: always
  script:
    - shamanops repository-check
# ------------------------------------------------------------------------------
# Stage 2 - Build ##############################################################
image-build-and-push:
  tags:
    - self-hosted
  stage: build
  script:
    - shamanops image-build
  needs: ["repository-check"]
image-check:
  tags:
    - self-hosted
  stage: build
  script:
    - shamanops image-check
  needs: ["repository-check", "image-build-and-push"]
# ------------------------------------------------------------------------------
# Stage 3 - Analysis ###########################################################
security_check:
  tags:
    - self-hosted
  stage: analysis
  needs: ["image-check"]
  rules:
    - if: $security_check_enabled == 'true' && $security_check_blocker == 'true'
      when: on_success
      allow_failure: false
    - if: $security_check_enabled == 'true' && $security_check_blocker != 'true'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops security-check
sast_check:
  tags:
    - self-hosted
  stage: analysis
  needs: ["image-check"]
  rules:
    - if: $code_quality_check_enabled == 'true' && $code_quality_check_blocker == 'true'
      when: on_success
      allow_failure: false
    - if: $code_quality_check_enabled == 'true' && $code_quality_check_blocker != 'true'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops sast-check
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - DEV environment #########################################################
approvals-dev:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: security_check
      optional: true
    - job: sast-check
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $environments != 'mid' && $shamanopsApprovalsDev == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops approvals dev
db-versioning-dev:
  tags:
    - self-hosted
  stage: deploy
  needs:
    - job: approvals-dev
      optional: true
    - job: security_check
      optional: true
    - job: sast-check
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $environments != 'mid' && $db_versioning_enabled == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops db-versioning dev
app-create-and-deploy-dev:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $environments != 'mid'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy dev
# Deploy - DYNAMIC environment #############################################
app-create-and-deploy-dynamic-envs:
  tags:
    - self-hosted
  stage: deploy
  needs:
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $shamanopsDynamicEnvsEnabled == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops dynamic-envs
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - STG environment #########################################################
approvals-stg:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $shamanopsApprovalsStg == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops approvals stg
db-versioning-stg:
  tags:
    - self-hosted
  stage: deploy
  needs:
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: approvals-stg
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal' && $db_versioning_enabled == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops db-versioning stg
app-create-and-deploy-stg:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: approvals-stg
      optional: true
    - job: db-versioning-stg
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $environments != 'minimal'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy stg
# ------------------------------------------------------------------------------
# Stage 5 - Deploy - PROD environment #########################################################
functional_analysis:
  tags:
    - self-hosted
  stage: deploy
  needs: ["app-create-and-deploy-stg"]
  rules:
    - if: $functional_analysis_enabled == 'true' && $functional_analysis_blocker == 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: false
    - if: $functional_analysis_enabled == 'true' && $functional_analysis_blocker != 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops functional-check
stress_test:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: app-create-and-deploy-stg
      optional: false
    - job: functional_analysis
      optional: false
  rules:
    - if: $stress_check_enabled == 'true' && $stress_check_blocker == 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: false
    - if: $stress_check_enabled == 'true' && $stress_check_blocker != 'true' && $environments != 'minimal'
      when: on_success
      allow_failure: true
    - when: never
  script:
    - shamanops stress-check
approvals-prod:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: approvals-stg
      optional: true
    - job: db-versioning-stg
      optional: true
    - job: app-create-and-deploy-stg
      optional: true
    - job: functional_analysis
      optional: true
    - job: stress_test
      optional: true
    - job: image-check
      optional: false
  rules:
    - if: $shamanopsApprovalsProd == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops approvals prod
db-versioning-prod:
  tags:
    - self-hosted
  stage: deploy
  needs:
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: approvals-stg
      optional: true
    - job: db-versioning-stg
      optional: true
    - job: app-create-and-deploy-stg
      optional: true
    - job: approvals-prod
      optional: true
    - job: image-check
      optional: false
    - job: functional_analysis
      optional: true
    - job: stress_test
      optional: true
  rules:
    - if: $db_versioning_enabled == 'true'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops db-versioning prod
app-create-and-deploy-prod:
  tags:
    - self-hosted
  stage: deploy
  needs: 
    - job: approvals-dev
      optional: true
    - job: db-versioning-dev
      optional: true
    - job: app-create-and-deploy-dev
      optional: true
    - job: app-create-and-deploy-dynamic-envs
      optional: true
    - job: approvals-stg
      optional: true
    - job: db-versioning-stg
      optional: true
    - job: app-create-and-deploy-stg
      optional: true
    - job: approvals-prod
      optional: true
    - job: db-versioning-prod
      optional: true
    - job: image-check
      optional: false
    - job: functional_analysis
      optional: true
    - job: stress_test
      optional: true
  rules:
    - when: on_success
      allow_failure: false
  script:
    - shamanops app-create-and-deploy prod
app-create-and-deploy-drp:
  tags:
    - self-hosted
  stage: deploy
  needs: ["app-create-and-deploy-prod"]
  rules:
    - if: $environments == 'full-with-drp'
      when: on_success
      allow_failure: false
    - when: never
  script:
    - shamanops app-create-and-deploy drp
################################################################################
